[input]
base_directory = "_index/"
url_prefix = "/"
files = [
  {path = "about.txt",                                  url = "about",                                  title = "About"},
  {path = "documentation.txt",                          url = "documentation",                          title = "Documentation"},
  {path = "documentation/architecture.txt",             url = "documentation/architecture",             title = "Architecture"},
  {path = "documentation/attributes.txt",               url = "documentation/attributes",               title = "Nix attributes"},
  {path = "documentation/changelog.txt",                url = "documentation/changelog",                title = "Changelog"},
  {path = "documentation/ci.txt",                       url = "documentation/ci",                       title = "Continuous integration"},
  {path = "documentation/clis.txt",                     url = "documentation/clis",                     title = "Command-line interfaces"},
  {path = "documentation/deployment.txt",               url = "documentation/deployment",               title = "Deployments"},
  {path = "documentation/emails.txt",                   url = "documentation/emails",                   title = "Emails"},
  {path = "documentation/environments.txt",             url = "documentation/environments",             title = "Environments"},
  {path = "documentation/forms.txt",                    url = "documentation/forms",                    title = "Forms"},
  {path = "documentation/library.txt",                  url = "documentation/library",                  title = "Library"},
  {path = "documentation/live-data.txt",                url = "documentation/live-data",                title = "Live data"},
  {path = "documentation/machine.txt",                  url = "documentation/machine",                  title = "Machine"},
  {path = "documentation/man-pages.txt",                url = "documentation/man-pages",                title = "Man pages"},
  {path = "documentation/messages.txt",                 url = "documentation/messages",                 title = "Messages"},
  {path = "documentation/nix.txt",                      url = "documentation/nix",                      title = "Nix"},
  {path = "documentation/objects.txt",                  url = "documentation/objects",                  title = "Objects"},
  {path = "documentation/objects/contracts.txt",        url = "documentation/objects/contracts",        title = "Contracts"},
  {path = "documentation/objects/entities.txt",         url = "documentation/objects/entities",         title = "Entities"},
  {path = "documentation/objects/invoices.txt",         url = "documentation/objects/invoices",         title = "Invoices"},
  {path = "documentation/objects/units.txt",            url = "documentation/objects/units",            title = "Units"},
  {path = "documentation/objects/users.txt",            url = "documentation/objects/users",            title = "Users"},
  {path = "documentation/orders.txt",                   url = "documentation/orders",                   title = "Orders"},
  {path = "documentation/permissions.txt",              url = "documentation/permissions",              title = "Permissions"},
  {path = "documentation/processes.txt",                url = "documentation/processes",                title = "Processes"},
  {path = "documentation/processes/signup.txt",         url = "documentation/processes/signup",         title = "Sign up"},
  {path = "documentation/queues.txt",                   url = "documentation/queues",                   title = "Queues"},
  {path = "documentation/quotations.txt",               url = "documentation/quotations",               title = "Quotations"},
  {path = "documentation/scenarios.txt",                url = "documentation/scenarios",                title = "Scenarios"},
  {path = "documentation/scenarios/quotation-flow.txt", url = "documentation/scenarios/quotation-flow", title = "Quotations flow"},
  {path = "documentation/sitemap.txt",                  url = "documentation/sitemap",                  title = "Sitemap"},
  {path = "documentation/smart.txt",                    url = "documentation/smart",                    title = "Smart"},
  {path = "documentation/source.txt",                   url = "documentation/source",                   title = "Source code"},
  {path = "documentation/state-0.txt",                  url = "documentation/state-0",                  title = "State 0"},
  {path = "documentation/state.txt",                    url = "documentation/state",                    title = "State"},
  {path = "documentation/tests.txt",                    url = "documentation/tests",                    title = "Tests"},
  {path = "documentation/time.txt",                     url = "documentation/time",                     title = "Time"},
  {path = "documentation/ubl.txt",                      url = "documentation/ubl",                      title = "UBL"},
  {path = "documentation/validation-data.txt",          url = "documentation/validation-data",          title = "Validation data"},
  {path = "documentation/validation.txt",               url = "documentation/validation",               title = "Validation"},
  {path = "documentation/views.txt",                    url = "documentation/views",                    title = "Views"},
]
